name: sentry_file
description: An integration which adds support for performance tracing for dart.io.File.
version: 7.9.0
publish_to: none
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/dart/configuration/integrations/file/

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  sentry: 
    git: https://github.com/kumsumit/sentry.git
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  coverage: ^1.7.2
  mockito: ^5.4.4
  yaml: ^3.1.2 # needed for version match (code and pubspec)
